#![allow(clippy::needless_range_loop)]

use crate::error::StcError;
use crate::parity::{effective_height, htilde_for_rate};

/// Configuration for the STC encoder/decoder.
pub struct StcConfig {
    /// Constraint height h. Typical range 5–12. Higher = better distortion, slower (O(n·2^h)).
    pub constraint_height: u8,
}

impl Default for StcConfig {
    fn default() -> Self {
        Self {
            constraint_height: 7,
        }
    }
}

pub struct StcEncoder {
    config: StcConfig,
}

pub struct StcDecoder {
    config: StcConfig,
}

impl StcEncoder {
    pub fn new(config: StcConfig) -> Self {
        Self { config }
    }

    /// Embed `message` bits into `cover` bits with per-bit costs.
    pub fn embed(&self, cover: &[u8], costs: &[f64], message: &[u8]) -> Result<Vec<u8>, StcError> {
        let n = cover.len();
        let m = message.len();

        if m == 0 {
            return Ok(cover.to_vec());
        }

        if n == 0 || !n.is_multiple_of(m) {
            return Err(StcError::LengthMismatch {
                cover: n,
                message: m,
            });
        }

        // If all positions are wet and the syndrome doesn't already match, fail early.
        if costs.iter().all(|&c| c.is_infinite()) {
            let current_syndrome = compute_syndrome(cover, m, self.config.constraint_height);
            if current_syndrome != message {
                return Err(StcError::InfeasibleWetPaper);
            }
            return Ok(cover.to_vec());
        }

        viterbi_embed(cover, costs, message, self.config.constraint_height)
    }
}

/// Block-constrained Viterbi STC embedding.
///
/// The trellis has 2^h states representing a sliding syndrome window of h rows.
/// Each cover position updates the state: state ^= y_i * H̃_col(i % w).
/// At the end of each block of w positions, the LSB of the state must equal
/// message[b]; it is then right-shifted out. After m blocks the state must be 0.
///
/// Uses the h×w H̃ sub-matrix generated by `htilde_for_rate(h, w)`.
fn viterbi_embed(cover: &[u8], costs: &[f64], message: &[u8], h: u8) -> Result<Vec<u8>, StcError> {
    let n = cover.len();
    let m = message.len();
    let w = n / m;
    let h = effective_height(h, w);
    let num_states = 1usize << h;
    let state_mask = num_states - 1;
    let half_states = num_states / 2;

    let cols = htilde_for_rate(h as u8, w);

    let mut dp = vec![f64::INFINITY; num_states];
    dp[0] = 0.0;

    // traceback_y[i][s]    = y bit chosen when ending at state s after column i
    // traceback_prev[i][s] = predecessor state before column i
    let mut traceback_y: Vec<Vec<u8>> = vec![vec![0u8; num_states]; n];
    let mut traceback_prev: Vec<Vec<u32>> = vec![vec![u32::MAX; num_states]; n];

    // For each block end: pre-shift state for each post-shift state.
    let mut block_preshift: Vec<Vec<u32>> = vec![vec![u32::MAX; half_states]; m];

    for block in 0..m {
        let msg_bit = message[block] as usize;
        let col_start = block * w;

        for j in 0..w {
            let i = col_start + j;
            let h_col_mask = cols[j] & (state_mask as u64);
            let x_bit = cover[i] as u64;
            let cost_flip = costs[i];

            let mut new_dp = vec![f64::INFINITY; num_states];

            for s in 0..num_states {
                let cur_cost = dp[s];
                if cur_cost.is_infinite() {
                    continue;
                }
                for y in 0u64..=1 {
                    if y != x_bit && cost_flip.is_infinite() {
                        continue;
                    }
                    let ns = (s as u64 ^ (y * h_col_mask)) as usize;
                    let bit_cost = if y != x_bit { cost_flip } else { 0.0 };
                    let c = cur_cost + bit_cost;
                    if c < new_dp[ns] {
                        new_dp[ns] = c;
                        traceback_y[i][ns] = y as u8;
                        traceback_prev[i][ns] = s as u32;
                    }
                }
            }

            dp = new_dp;
        }

        // Block boundary: LSB must equal msg_bit; right-shift to consume it.
        let mut shifted_dp = vec![f64::INFINITY; num_states];
        for s in 0..num_states {
            if dp[s].is_infinite() {
                continue;
            }
            if s & 1 == msg_bit {
                let new_s = s >> 1;
                let cost = dp[s];
                if cost < shifted_dp[new_s] {
                    shifted_dp[new_s] = cost;
                    block_preshift[block][new_s] = s as u32;
                }
            }
        }
        dp = shifted_dp;
    }

    if dp[0].is_infinite() {
        return Err(StcError::InfeasibleWetPaper);
    }

    // Traceback starting from final state 0.
    let mut stego = vec![0u8; n];
    let mut state = 0usize;

    for block in (0..m).rev() {
        let pre_shift = block_preshift[block][state] as usize;
        let col_start = block * w;

        let mut cur_state = pre_shift;
        let mut col_bits = vec![0u8; w];

        for j in (0..w).rev() {
            let i = col_start + j;
            col_bits[j] = traceback_y[i][cur_state];
            cur_state = traceback_prev[i][cur_state] as usize;
        }

        stego[col_start..col_start + w].copy_from_slice(&col_bits);

        state = cur_state;
    }

    Ok(stego)
}

impl StcDecoder {
    pub fn new(config: StcConfig) -> Self {
        Self { config }
    }

    /// Extract a message from a stego bit vector.
    pub fn extract(&self, stego: &[u8], message_len: usize) -> Vec<u8> {
        compute_syndrome(stego, message_len, self.config.constraint_height)
    }
}

/// Compute H·y (mod 2) — syndrome extraction matching the encoder's trellis convention.
///
/// For position i in block b = i/w, column j = i%w of H̃ contributes h bits.
/// State bit k is consumed at block b+k (right-shift removes LSB at each block end),
/// so H̃[k][j] maps to message row (b + k).
fn compute_syndrome(bits: &[u8], message_len: usize, h: u8) -> Vec<u8> {
    if message_len == 0 {
        return vec![];
    }
    let n = bits.len();
    let w = n / message_len;
    let h = effective_height(h, w);
    let cols = htilde_for_rate(h as u8, w);

    let mut syndrome = vec![0u8; message_len];

    for i in 0..n {
        if bits[i] == 0 {
            continue;
        }
        let b = i / w;
        let j = i % w;
        let h_col = cols[j];

        for k in 0..h {
            if (h_col >> k) & 1 == 0 {
                continue;
            }
            let r = b + k;
            if r < message_len {
                syndrome[r] ^= 1;
            }
        }
    }

    syndrome
}
